name: akademik
description: E-learning siakad.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.3.3+1
  google_fonts: 5.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  fluttertoast: ^8.2.5
  percent_indicator: ^4.2.3
  http: ^1.2.1
  provider: ^6.1.2
  timeline_calendar: ^1.0.1
  url_launcher: ^6.3.0
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

